name: compile-check on pull-request to master or main

on:
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: compile and test
        uses: payfree-io/.github/.github/workflows/gradle-tasks.yml@main
        #env:
          #ORG_GRADLE_PROJECT_environment: dev
        with:
          gradle-tasks: build
      - name: Upload test-results
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: test-results
          path: '**/build/reports/'

