name: "call gradle tasks"
description: "setup java, validate gradle and call specified gradle task"

inputs:
  gradle-tasks:
    required: true
    description: "the gradle tasks to be executed"

runs:
  using: "composite"
  steps:
    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: 16
        java-package: jdk
        architecture: x64
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v1
    - name: gradle execute
      uses: gradle/gradle-build-action@v2
      with:
        arguments: --no-daemon --no-configuration-cache ${{ inputs.gradle-tasks }}
